# -*- coding: utf-8 -*-
"""Clase3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I8HAXMuE1wTTmU7hFOj6HQqADmZuENLm
"""

import sqlite3
from sqlite3 import Error
con = sqlite3.connect("mitienda3.db")

ls-la

cursor0bj = con.cursor()

def sql_connection():

     try:
       con = sqlite3.connect(":memory")

       print("La conexion ha sido creado con exito")

     except Error:
         print(Error)

     finally:
           con.close()

sql_connection()

import sqlite3

from sqlite3 import Error

def sql_connection():

  try:
      con = sqlite3.connect('mitienda3.db')

      return con

  except Error:

      print(Error)

def sql_table(con):

    cursorObj = con.cursor()

    cursorObj.execute("CREATE TABLE productos(id integer PRIMARY KEY, producto text, precio real)")

    con.commit()


sql_table(con)

import sqlite3

con = sqlite3.connect('mitienda3.db')

def sql_insert(con):

  cursorObj.execute("INSERT INTO productos VALUES(1, 'Oreo', 0.80,)")

con.commit()

con = sqlite3.connect('mitienda3.db')

def sql_insert(con, entities):

    cursorObj = con.cursor()
    
    cursorObj.execute('INSERT INTO productos(id, producto, precio) VALUES(?, ?, ?)', entities)
    
    con.commit()



entities = (3, 'Gaseosa', 10.5)

sql_insert(con,entities)